parser: "@typescript-eslint/parser"
parserOptions:
  project:
    - "./packages/*/tsconfig.json"
  tsconfigRootDir: "."
plugins:
  - "@typescript-eslint"
  - "only-warn"
extends:
  - "plugin:@typescript-eslint/strict"
  - "plugin:@next/next/recommended"
  - "airbnb-base"
  - "airbnb-typescript/base"
rules:
  "@typescript-eslint/quotes": [warn, double]
  "@typescript-eslint/indent": [warn, 2]
  "@typescript-eslint/consistent-type-imports": [warn, {
    prefer: type-imports,
    disallowTypeAnnotations: false
  }]
  "@typescript-eslint/consistent-type-exports": warn
  "@typescript-eslint/no-unnecessary-type-assertion": warn
  "@typescript-eslint/array-type": [warn, {
    default: array,
    readonly: array
  }]
  "max-classes-per-file": off
  "@typescript-eslint/explicit-member-accessibility": [warn, accessibility: explicit]
  "@typescript-eslint/method-signature-style": [warn, method]
  "@typescript-eslint/no-empty-function": [warn, allow: [constructors]]
  "@typescript-eslint/no-extraneous-class": [warn, allowWithDecorator: true]
  "@typescript-eslint/lines-between-class-members": [warn, always, exceptAfterSingleLine: true]
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-invalid-void-type": off
  "@typescript-eslint/no-explicit-any": off
  "@next/next/no-html-link-for-pages": off
  "import/extensions": off
  "import/prefer-default-export": off
  "import/no-default-export": off
  "import/order": [error, {
    groups: [index, sibling, parent, internal, external, builtin, object, type]
  }]
  "no-spaced-func": off
  "prefer-destructuring": off
  "class-methods-use-this": off
  "yoda": [warn, never, onlyEquality: true]
  "max-len": [warn, {
    code: 120,
    ignoreComments: true,
    ignorePattern: "(^import .*?)|(^export .*?)|(^ *describe.*?)|(^ *it.*?)",
  }]
  "consistent-return": off
